-- Dec 18 — Complex Joins + Multiple Tables

-- 1. SETUP
-- We will assume the basic store tables (customers, orders, products, order_items) exist from previous days.
-- If not, you may need to run the setup from Dec 14 or Dec 10 first.
-- Here, we will add an EMPLOYEES table for Self Join practice, and ensure other tables are ready.

CREATE TABLE IF NOT EXISTS employees (
    employee_id INTEGER PRIMARY KEY,
    name TEXT,
    role TEXT,
    manager_id INTEGER -- Self referencing Foreign Key
);

-- Reset Employees
DELETE FROM employees;

INSERT INTO employees (employee_id, name, role, manager_id) VALUES
(1, 'Idil Hassan', 'CEO', NULL),
(2, 'Bile Yussuf', 'Sales Manager', 1),
(3, 'Cawo Mohamed', 'Tech Lead', 1),
(4, 'Dalmar Abdi', 'Sales Rep', 2),
(5, 'Ebyan Ali', 'Developer', 3),
(6, 'Farah Omar', 'Intern', 5);

-- Small tables for Cross Join practice
CREATE TABLE IF NOT EXISTS colors (color_name TEXT);
CREATE TABLE IF NOT EXISTS sizes (size_name TEXT);

DELETE FROM colors; DELETE FROM sizes;
INSERT INTO colors VALUES ('Red'), ('Blue'), ('Green');
INSERT INTO sizes VALUES ('S'), ('M'), ('L');


-- 2. EXERCISES

-- Ex 1: MULTI-TABLE JOIN
-- List the Customer Name, Product Name, and Order Date for all items sold in 2024.
-- Hint: Join Customers -> Orders -> Order_Items -> Products
SELECT 
    c.name AS customer_name, 
    p.name AS product_name, 
    o.order_date
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE o.order_date LIKE '2024%';


-- Ex 2: SELF JOIN
-- List every employee's name alongside their Manager's name.
-- Include employees even if they don't have a manager (like the CEO).
SELECT 
    e.name AS employee_name, 
    m.name AS manager_name
FROM employees e
LEFT JOIN employees m ON e.manager_id = m.employee_id;


-- Ex 3: CROSS JOIN
-- Generate all possible SKUs (combinations) of Color and Size.
SELECT 
    c.color_name, 
    s.size_name
FROM colors c
CROSS JOIN sizes s;


-- Ex 4: UNION
-- We want a single list of all "people" we deal with: Customers and Employees.
-- Return a single column called 'Person_Name' and a column 'Type' ('Customer' or 'Employee').
SELECT name AS Person_Name, 'Customer' AS Type FROM customers
UNION
SELECT name AS Person_Name, 'Employee' AS Type FROM employees;


-- Ex 5: CHALLENGE
-- Find the Total Revenue generated by each SALES REP (managed by 'Bile Yussuf').
-- Note: This is tricky. In this schema, we don't link orders to employees explicitly.
-- So let's solve a different riddle:
-- List all Customers who have bought 'Electronics' AND 'Apparel'.
-- Hint: You might need to join tables and use INTERSECT, or use self-joins on a subquery.
-- A simpler approach using existing tools:
SELECT c.name 
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE p.category = 'Electronics'
INTERSECT
SELECT c.name 
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE p.category = 'Apparel';
